### ISSUE TITLE
onDataChange

### ISSUE THREAD

**Issue by Rafelcf** [Alex228q/CalendarCompose#1]
How can I get the date complete of the day onclick?

**Comment by Alex228q** [comment]
add clickable to Box modifier 

itemsIndexed(dates) { index, dayInMonth ->
                    Box(
                        contentAlignment = Alignment.Center,
                        modifier = Modifier
                            .size(50.dp)
                              .clickable {
                                Log.d("TAG",dayInMonth.toString())
                            }
                    )

**Comment by Rafelcf** [comment]
But how does the date text change?
text = annotatedString,?

**Comment by Alex228q** [comment]
add mutable state for  index(our date) into itemsIndex and then change to your value in clickable

itemsIndexed(dates) { index, dayInMonth ->
                    var indexPlusOne by remember {
                        mutableStateOf((index + 1).toString())
                    }
                    Box(
                        contentAlignment = Alignment.Center,
                        modifier = Modifier
                            .size(50.dp)
                            .clickable {
                                indexPlusOne = "Hi"
                            }
                    ) {

                        val color = when (dayInMonth.toString()) {
                            in days -> Color(0Xff6FF089)
                            in evening -> Color(0XFF4FBBFF)
                            in night -> Color(0XFFFF83A4)
                            else -> Color.Transparent
                        }


                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                style = MaterialTheme.typography.titleMedium,
                                fontSize = 20.sp,
                                text = indexPlusOne.toString(),
                                color = if (currentDate == dayInMonth) Color.Red else MaterialTheme.colorScheme.onPrimary
                            )
                            HorizontalDivider(
                                thickness = 4.dp,
                                modifier = Modifier
                                    .width(14.dp)
                                    .clip(RoundedCornerShape(60)),
                                color = color
                            )
                        }
                    }
                }

**Comment by Alex228q** [comment]
upps

**Comment by Alex228q** [comment]
this 
itemsIndexed(dates) { index, dayInMonth ->
                    var indexPlusOne by remember {
                        mutableStateOf((index + 1).toString())
                    }
                    Box(
                        contentAlignment = Alignment.Center,
                        modifier = Modifier
                            .size(50.dp)
                            .clickable {
                                indexPlusOne = "Hi"
                            }
                    )
